name: lean4
version: "4.7.0"
summary: Lean 4 programming language and theorem prover 
description: |
  Lean is a functional programming language that makes it easy
  to write correct and maintainable code. You can also use Lean
  as an interactive theorem prover. Lean programming primarily
  involves defining types and functions. This allows your focus
  to remain on the problem domain and manipulating its data,
  rather than the details of programming.

base: core22
confinement: strict
compression: lzo

parts:
  lean4:
    plugin: cmake
    source: https://github.com/leanprover/lean4.git
    source-branch: v$SNAPCRAFT_PROJECT_VERSION
    source-type: git
    # source-depth: 1
    build-packages:
      - git
      - libgmp-dev
      - ccache
      - clang
    override-build: |
      cmake $CRAFT_PART_SRC \
        -D CMAKE_C_COMPILER=/usr/bin/clang \
        -D CMAKE_CXX_COMPILER=/usr/bin/clang++ \
        --install-prefix $CRAFT_PART_INSTALL/usr
      make -j$(nproc) stage3 install
  leanc:
    plugin: nil
  lake:
    plugin: nil
    stage-packages:
      - git
  leanmake:
    plugin: nil


apps:
  leanc:
    command: /usr/bin/leanc
    plugs:
      - home
  lean:
    command: /usr/bin/leanc
    plugs:
      - home
  lake:
    command: /usr/bin/lake
    plugs:
      - home
  leanmake:
    command: /usr/bin/leanmake
    plugs:
      - home
