name: ghc
version: "9.0.1"
summary: The Glorious Glasgow Haskell Compiler.
description: |
  GHC is a state-of-the-art, open source compiler and interactive
  environment for the functional language Haskell.

base: core22
confinement: strict

parts:
  ghc:
    plugin: nil
    source-type: git
    source: https://gitlab.haskell.org/ghc/ghc.git
    override-build: |
      # Seems like a bug in snapcraft? '|| true' shouldn't be necessary here
      bootstrap=$(apt-cache policy ghc | grep -o -m 1 '[0-9]*\.[0-9]*\.[0-9]*') || true

      # Build the newest version of haskell by bootstrapping from the version built in previous iteration of loop.
      for release in $(git tag -l *-release | sort --version-sort | awk "/$bootstrap/,/$SNAPCRAFT_PROJECT_VERSION/" | tail -n+2); do

        # Install deps for curently installed version of hashell
        cabal update
        cabal install cabal-install --overwrite-policy=always
        cabal install happy --overwrite-policy=always
        cabal install alex --overwrite-policy=always

        # Build new version of haskell
        ls -A | grep -v ".git" | xargs rm -rf
        git reset --hard
        git checkout $release
        ls -A | grep -v ".git" | xargs rm -rf
        git reset --hard
        git submodule update --init --recursive
        git status
        autoreconf || true
        ./boot || true
        ./configure || true
        autoreconf
        ./boot
        ./configure
        make -j$(nproc) && make install
        ghc --version
        exit 1
      done
    build-packages:
      - ghc
      - autoconf
      - automake
      - pkg-config
      - python3-sphinx
      - build-essential
      - cabal-install
      - hscolour

apps:
  ghc:
    command: /usr/bin/ghc
    plugs:
      - home
