name: ghc
version: "9.0.1"
summary: The Glorious Glasgow Haskell Compiler.
description: |
  GHC is a state-of-the-art, open source compiler and interactive
  environment for the functional language Haskell.

base: core22
confinement: strict

parts:
  ghc:
    plugin: nil
    source-type: git
    source: https://gitlab.haskell.org/ghc/ghc.git
    override-build: |
      #echo "$SNAPCRAFT_PROJECT_VERSION"
      #apt-cache policy ghc
      for release in $(git tag -l *-release | awk '/8.8.4/,/9.8.2/' | tail -n+2); do
        ls -A | grep -v ".git" | xargs rm -rf
        git reset --hard
        git checkout $release
        ls -A | grep -v ".git" | xargs rm -rf
        git reset --hard
        git submodule update --init --recursive
        git status
        autoreconf || true
        ./boot || true
        ./configure || true
        autoreconf
        ./boot
        ./configure
        make -j$(nproc) && make install
        ghc --version
      done
    build-packages:
      - ghc
      - autoconf
      - automake
      - build-essential
      - happy
      - alex
      - hscolour

apps:
  ghc:
    command: /usr/bin/ghc
    plugs:
      - home
