name: ghc
version: "9.8.2"
summary: The Glorious Glasgow Haskell Compiler.
description: |
  GHC is a state-of-the-art, open source compiler and interactive
  environment for the functional language Haskell.

base: core22
confinement: strict

parts:
  ghc:
    plugin: nil
    source-type: git
    source: https://gitlab.haskell.org/ghc/ghc.git
    override-build: |
      echo "$SNAPCRAFT_PROJECT_VERSION"
      apt-cache policy ghc
      exit 1
      #./boot
      #./configure
      #./hadrian/build -j8
    build-packages:
      - ghc
      - autoconf
      - automake
      - build-essential
      - happy
      - alex
      - hscolour

apps:
  ghc:
    command: ghc
    plugs:
      - home
